version: "3.9"
services:
  db:
    image: postgres
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  peerjs-server:
    image: peerjs/peerjs-server
    command: ["--port", "9000", "--path", "/"]
    ports:
      - 443:9000
  app:
    image: kurovale/kuro-cams
    build: ./
    environment:
      - DATABASE_URL=ecto://postgres:pass@db:5432/postgres
      - PEERJS_SERVER=localhost
      # - PHX_HOST=
    ports:
      - 4000:4000
    depends_on:
        db:
          condition: service_healthy
